name: sync-template-repo-changes
on:
  schedule:
  - cron:  "0 0 1 * *"
  workflow_dispatch:
  workflow_call:
    secrets:
      TEMPLATE_SYNC_TOKEN:
        required: true

permissions: 
  contents: write
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    environment: template-sync
    
    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Use the obtained token
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.3
        with:
          github_token: ${{ secrets.TEMPLATE_SYNC_TOKEN }}
          source_repo_path: themitchell/marp-template
